server:
  port: 8765

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      name: gateway-service